---
- name: configure apache webserver 
  hosts: all
  gather_facts: no
  tasks:
      - name: Install apache
        yum:
            name: httpd
            state: present
      - name: enabled httpd service
        service:
            name: httpd
            state: started
            enabled: true
      - name: remove html directory
        file:
            path: "/var/www/html"
            state: absent
      - name: synchronize a directory from the local to the remote machine
        synchronize:
            src: html
            dest: /var/www/
            recursive: yes
        notify: Restart apache

  handlers:
      - name: Restart apache
        service:
            name: httpd
            state: restarted
